
let helpInfo: [String:[[String:String]]] = [
    "Operating Cash Flow": [
        [
            "title": "What is it?",
            "text": "The amount of money generated by a company's normal business operations."
        ],
        [
            "title": "Where to find it?",
            "text": "On a company’s cash flow statement. You can find this on morningstar.com or the company's investor relations page."
        ],
        [
            "title": "",
            "text": "Also known as 'Net Cash Provided From Operating Activities'"
        ]
    ],
    "Maintenance Capital Expenditures": [
        [
            "title": "What is a Capital Expenditure?",
            "text": "Money used by a company to acquire, upgrade, or maintain physical assets."
        ],
        [
            "title": "What is Maintenance Capital Expenditures?",
            "text": "Money that a company spends to maintain the business."
        ],
        [
            "title": "Where to find it?",
            "text":  "The 'Investing Activities' portion on the cash flow statement."
        ],
        [
            "title": "",
            "text": "Also known as 'Purchase of Property Plant & Equipment'"
        ],
        [
            "title": "Tip",
            "text": "If you can’t figure out how much of a company’s capital expenditures are allocated for maintenance, you can use the company’s Total Capital Expenditures (Purchase of Property, Plant, & Equipment) and subtract it from the Operating Cash Flow. This number will give you the company’s Free Cash Flow."
        ]
    ],
    "Number of Years": [
        [
            "title": "",
            "text": "How many years into the future you want to predict the cash flow of the business."
        ]
    ],
    "Future Growth Rate": [
        [
            "title": "",
            "text": "The rate at which you believe the company will grow its cash flows in the future."
        ]
    ],
    "Desired Rate of Return": [
        [
            "title": "",
            "text": "The rate of return you want with this investment."
        ]
    ],
    "Outstanding Shares": [
        [
            "title": "",
            "text": "The number of shares currently available for sale."
        ]
    ]
]
