
let helpInfo: [String:[[String:String]]] = [
    "Operating Cash Flow": [
        [
            "title": "Definition",
            "text": "The amount of money generated by a company's normal business operations."
        ],
        [
            "title": "Where to find it?",
            "text": "On a company’s cash flow statement. You can find this on morningstar.com or the company's investor relations page."
        ],
        [
            "title": "Another Name",
            "text": "Also known as 'Net Cash Provided From Operating Activities'"
        ],
        [
            "title": "Example",
            "text": "A lemonade stand’s main purpose is selling lemonade to customers. Therefore, the amount of money a lemonade stand makes selling lemonade to customers is its operating cash flow."
        ]
    ],
    "Maintenance Capital Expenditures": [
        [
            "title": "What is a Capital Expenditure?",
            "text": "Money used by a company to acquire, upgrade, or maintain physical assets."
        ],
        [
            "title": "What is Maintenance Capital Expenditures?",
            "text": "Money that a company spends to maintain the business."
        ],
        [
            "title": "Where to find it?",
            "text":  "The 'Investing Activities' portion on the cash flow statement."
        ],
        [
            "title": "",
            "text": "Also known as 'Purchase of Property Plant & Equipment'"
        ],
        [
            "title": "Tip",
            "text": "If you can’t figure out how much of a company’s capital expenditures are allocated for maintenance, you can use the company’s Total Capital Expenditures (Purchase of Property, Plant, & Equipment) and subtract it from the Operating Cash Flow. This number will give you the company’s Free Cash Flow."
        ],
        [
            "title": "Example",
            "text": "Ice is a key component when operating a lemonade stand. How else are you going to serve cold, refreshing lemonade? An even more important component is the ice machine that generates the ice cubes you use. If your ice machine breaks, you’ll need to spend money to fix it for your lemonade stand to continue to operate."
        ]
    ],
    "Number of Years": [
        [
            "title": "Definition",
            "text": "How many years into the future you want to predict the cash flow of the business."
        ]
    ],
    "Future Growth Rate": [
        [
            "title": "Definition",
            "text": "The rate at which you believe the company will grow its cash flows in the future."
        ],
        [
            "title": "Example",
            "text": "Say you want to invest in this lemonade stand you’ve seen in your town. You notice they’re growing their numbers across the board at a very consistent 15% per year - and have been doing so for quite some time. In this scenario, it’d be fair to say you can expect this lemonade stand to continue to grow at 15% into the future."
        ]
    ],
    "Desired Rate of Return": [
        [
            "title": "Definition",
            "text": "The rate of return you want with this investment."
        ],
        [
            "title": "Example",
            "text": "As an investor, it’s important to know what kind of return you are willing to accept in exchange for the risk of investing your money. The lower your desired rate of return - the higher the price you’re willing to pay. The higher your desired rate of return - the lower the price you’re willing to pay."
        ]
    ],
    "Outstanding Shares": [
        [
            "title": "Definition",
            "text": "The number of shares currently available for sale."
        ],
        [
            "title": "Example",
            "text": "If you own a lemonade stand and decide you want to expand, but you need outside capital to do so, you could consider taking your business public so investors can lend you money. The number of outstanding shares is the number of shares you offer to investors to purchase. The investors that purchased those shares now own a portion of your lemonade stand business. In exchange for those shares of the lemonade stand, the company now has money that it can use to expand, grow, buy out competitors, etc."
        ]
    ]
]
